### ISSUE TITLE
[GRANT] Test 1

### ISSUE THREAD

**Issue by NerdGGuy** [NerdGGuy/GGrants#1]
### Terms and Conditions

- [X] If my proposal is funded, I agree to all terms and conditions in the [Grant Agreement]().
- [X] If my proposal is funded above $50,000, I am willing to provide [KYC information]() as outlined in the [Grant Agreement]().
- [X] I acknowledge that it is my responsibility to disclose any conflicts of interest related to my personal or professional relationship(s) with any Community Grants committee member.
- [X] I acknowledge that it is my responsiblity to adhere to the [ZCG Code of Conduct]().
- [X] I acknowledge it is my responsibility to post the details of this request on the [Community Forum]() for community input prior to the Community Grants committee discussing and voting on this request.

### Project Name

Test 1

### Project Description

This is my awesome descriptions of my awesome project.

### Requested Grant Amount

$10000USD

### Team Members

Matthew
John

### Startup Funding (delete this section if not applicable):
**Amount:** $XXX USD
**Initial Activities:**
- Set up project infrastructure

**Details:**
Describe in more detail what the startup funding will be used for and how it will help kick off the project.

### Milestone 1:
**Amount:** $XXX USD
**Deliverables:**
- Complete first prototype
- Conduct user testing

**Details:**
Provide a more comprehensive explanation of the first milestone, including the approach to developing the prototype and the methodology for user testing.

### Milestone 2:
**Amount:** $XXX USD
**Deliverables:**
- Refine product based on user feedback
- Launch beta version

**Details:**
Elaborate on how you plan to incorporate user feedback, what refinements are expected, and the strategy for launching the beta version.

(Add more milestones as needed)

### Total Grant Amount

10000

### Expected Outcomes

All the things

### Additional Information

Thanks
